### ISSUE TITLE
Error plug in Kicad 8.04 

### ISSUE THREAD

**Issue by BernardusArts** [Steffen-W/Import-LIB-KiCad-Plugin#24]
I got an error at the plug in (set to automatic).

![error_plug_in](https://github.com/user-attachments/assets/bb2f0a70-4209-4ad1-8c1e-f42b200b0e2f)

Kind Regards, Bernard

**Comment by Steffen-W** [comment]
The error puzzles me, as I don't really do anything with PDF documents. Would I accidentally import a PDF document or what do you mean. I would need a little more information. Does this happen when importing or when adjusting the settings. Does the error also occur when the download folder is empty?
