### ISSUE TITLE
KICAD7 3rd Party Envoirnment variable

### ISSUE THREAD

**Issue by ns2gupta** [Steffen-W/Import-LIB-KiCad-Plugin#8]
Hello Steffen, 

KiCAD7 has different envoirment variables. it gives me this error 

![Screenshot 2023-12-14 132905](https://github.com/Steffen-W/Import-LIB-KiCad-Plugin/assets/39019003/9bd0f555-df97-4f98-a080-acaeca35ef79)

these are the new variable names for KICAD7 - 
![image](https://github.com/Steffen-W/Import-LIB-KiCad-Plugin/assets/39019003/3186e430-2a03-4e94-8f50-80416b04e400)

**Comment by Steffen-W** [comment]
Hi @ns2gupta,

you need to import it for your own.
[including-the-imported-libraries-in-kicad)](https://github.com/Steffen-W/Import-LIB-KiCad-Plugin#including-the-imported-libraries-in-kicad)

Regards Steffen
